using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Content.Shared.AU14.Objectives;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.AU14.Objectives;

[GenerateTypedNameReferences]
public sealed partial class ObjectiveIntelWindow : FancyWindow
{
    public ObjectiveIntelWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(string objectiveId, string defaultTitle, List<ObjectiveIntelTierEntry> tiers, int unlockedTier, int factionPoints, Action<int>? unlockCallback = null)
    {
        Title = "Intel Window";

        tiers ??= new List<ObjectiveIntelTierEntry>();
        if (unlockedTier < 0) unlockedTier = 0;
        if (unlockedTier > tiers.Count) unlockedTier = tiers.Count;

        // Populate header and points

        ObjectiveIntelTitle.Text = $" {defaultTitle} ";

        nexttierlabel.Text = $"Next tier: {(unlockedTier >= tiers.Count ? "All tiers unlocked" : unlockedTier+ "/" + tiers.Count )}";

            FactionPointsLabel.Text = factionPoints.ToString();


         UnlockedBox.DisposeAllChildren();
         NextBox.DisposeAllChildren();

        // Show previously unlocked tiers (0 .. unlockedTier - 1)
        for (int i = 0; i < unlockedTier && i < tiers.Count; i++)
        {
            var tier = tiers[i];
            var container = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };
            var title = new Label { Text = tier.Title };
            var desc = new Label { Text = tier.Description };
            container.AddChild(title);
            container.AddChild(desc);
           UnlockedBox.AddChild(container);
        }

        // Next tier
        if (unlockedTier >= tiers.Count)
        {
            var all = new Label { Text = "All intel tiers unlocked.", HorizontalAlignment = HAlignment.Center };
             NextBox.AddChild(all);
        }
        else if (unlockedTier < tiers.Count)
        {
            var nextTier = tiers[unlockedTier];
            var container = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };
            var nextTitle = new Label { Text = nextTier.Title };
            var unlockBtn = new Button { Text = $"Unlock: [{nextTier.CostToUnlock}]", Disabled = unlockCallback == null };
            if (unlockCallback != null)
            {
                var idx = unlockedTier;
                unlockBtn.OnPressed += _ => unlockCallback(idx);
            }
            container.AddChild(nextTitle);
            container.AddChild(unlockBtn);
            NextBox.AddChild(container);
        }
    }
}
